/* SEO registry for the 35 curated matchup pages (/de/versus/<a>-gegen-<b>,
 * /en/versus/<a>-vs-<b>) — data source: src/data/matchups.json, generated by
 * scripts/simulate-matchups.mjs from 100 real engine battles per pairing.
 *
 * Slug scheme: DE uses the German names with „-gegen-", EN the English
 * species slugs with „-vs-". metaForPath() and restForLang() in seo.ts hook
 * in here so title/description carry the actual simulation result. */
import type { Lang } from './i18n-data';
import type { RouteMeta } from './seo';
import MATCHUPS_JSON from '@/data/matchups.json';

export interface MatchupKeyMove {
  slug: string;
  range: [number, number];
  pct: [number, number];
  eff: number;
}

export interface MatchupEntry {
  slugDe: string;
  slugEn: string;
  dexA: number;
  dexB: number;
  nameDeA: string;
  nameDeB: string;
  nameEnA: string;
  nameEnB: string;
  winsA: number;
  winsB: number;
  ties: number;
  medianTurns: number;
  speedA: number;
  speedB: number;
  typesA: string[];
  typesB: string[];
  setsA: string[];
  setsB: string[];
  setSourceA: 'wild' | 'assumed';
  setSourceB: 'wild' | 'assumed';
  movesA: MatchupKeyMove[];
  movesB: MatchupKeyMove[];
}

export interface MatchupsMeta {
  engine: string;
  format: string;
  level: number;
  battles: number;
  versionGroup: string;
  seedSchema: string;
}

export const MATCHUPS_META = MATCHUPS_JSON.meta as MatchupsMeta;
export const MATCHUPS = MATCHUPS_JSON.matchups as MatchupEntry[];

/** localized display names of a matchup entry */
export function matchupNames(m: MatchupEntry, lang: Lang): { a: string; b: string } {
  return lang === 'de' ? { a: m.nameDeA, b: m.nameDeB } : { a: m.nameEnA, b: m.nameEnB };
}

/** locale-aware slug of a matchup entry ('glurak-gegen-turtok' / 'charizard-vs-blastoise') */
export function matchupSlug(m: MatchupEntry, lang: Lang): string {
  return lang === 'de' ? m.slugDe : m.slugEn;
}

/** locale-aware rest path of a matchup page ('/versus/glurak-gegen-turtok') */
export function matchupRest(m: MatchupEntry, lang: Lang): string {
  return `/versus/${matchupSlug(m, lang)}`;
}

/** resolve a /versus/<slug> rest param to its entry (either locale's slug) */
export function resolveMatchupParam(param: string): MatchupEntry | null {
  return MATCHUPS.find((m) => m.slugDe === param || m.slugEn === param) ?? null;
}

/**
 * Translate a /versus/<slug> rest path into the target locale's slug.
 * Returns null when the rest is not a known matchup (caller keeps the rest).
 */
export function localizeMatchupRest(rest: string, lang: Lang): string | null {
  const match = rest.match(/^\/versus\/([^/]+)$/);
  if (!match) return null;
  const entry = resolveMatchupParam(match[1]);
  return entry ? matchupRest(entry, lang) : null;
}

const clamp = (text: string, max: number): string =>
  text.length <= max ? text : text.slice(0, text.slice(0, max).lastIndexOf(' ')) + '…';

/** per-matchup meta: the simulated result is the description's core number */
export function matchupMeta(m: MatchupEntry): RouteMeta {
  const de = matchupNames(m, 'de');
  const en = matchupNames(m, 'en');
  const b = MATCHUPS_META.battles;
  const lv = MATCHUPS_META.level;
  return {
    title: {
      de: `${de.a} vs. ${de.b}: Wer gewinnt? – Simulator-Ergebnis`,
      en: `${en.a} vs. ${en.b}: Who Wins? – Simulator Result`,
    },
    description: {
      de: clamp(
        `In ${b} simulierten Kämpfen (Level ${lv}, Standard-Sets) gewinnt ${de.a} ${m.winsA}-mal, ${de.b} ${m.winsB}-mal. Damage-Ranges, Initiative und Analyse.`,
        160,
      ),
      en: clamp(
        `Of ${b} simulated battles (level ${lv}, standard sets), ${en.a} wins ${m.winsA} and ${en.b} ${m.winsB}. Damage ranges, speed and analysis.`,
        160,
      ),
    },
    ogType: 'article',
  };
}
