/** Pokédex 2.0 — design tokens (design.md §2–§6) */
const TYPE_RGB = {
  normal: '169 176 181',
  fire: '255 122 69',
  water: '69 200 255',
  electric: '255 214 10',
  grass: '99 217 107',
  ice: '121 232 224',
  fighting: '244 96 94',
  poison: '199 125 255',
  ground: '222 184 114',
  flying: '167 139 250',
  psychic: '255 92 168',
  bug: '180 217 74',
  rock: '205 186 128',
  ghost: '157 127 237',
  dragon: '140 111 255',
  dark: '160 140 184',
  steel: '159 179 200',
  fairy: '255 154 213',
};

const typeColors = Object.fromEntries(
  Object.entries(TYPE_RGB).map(([k, v]) => [k, `rgb(${v} / <alpha-value>)`]),
);

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive) / <alpha-value>)', foreground: 'hsl(var(--destructive-foreground) / <alpha-value>)' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        /* design.md §2 — dark canvas */
        void: '#05060A',
        abyss: '#0A0C12',
        surface1: '#11141D',
        surface2: '#171B27',
        surface3: '#1F2433',
        hairline: 'rgba(255,255,255,0.07)',
        hairline2: 'rgba(255,255,255,0.14)',
        tx: { primary: '#F4F6FC', secondary: '#A8B0C4', muted: '#5E6680' },
        gold: '#F6C945',
        ember: '#FF8A6B',
        type: typeColors,
      },
      fontFamily: {
        display: ['Orbitron', 'sans-serif'],
        pixel: ['"Press Start 2P"', 'monospace'],
        sans: ['"Space Grotesk"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        xs: '6px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        pill: '999px',
      },
      maxWidth: { content: '1440px' },
      boxShadow: {
        xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        elevate: '0 8px 32px rgba(0,0,0,0.45)',
        'glow-gold': '0 0 24px rgba(246,201,69,0.35)',
        'glow-gold-lg': '0 0 0 1px rgba(246,201,69,0.55), 0 8px 40px rgba(246,201,69,0.30), 0 0 24px rgba(246,201,69,0.25)',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'inout-expo': 'cubic-bezier(0.65, 0, 0.35, 1)',
      },
      transitionDuration: { micro: '200ms', std: '400ms', page: '600ms', sheen: '600ms' },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'caret-blink': { '0%,70%,100%': { opacity: '1' }, '20%,50%': { opacity: '0' } },
        /* design.md §6 signature loops */
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.85' },
          '50%': { transform: 'scale(1.08)', opacity: '1' },
        },
        bob: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        'cue-bounce': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(6px)' } },
        marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        'spin-slow': { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        'spin-rev': { from: { transform: 'rotate(360deg)' }, to: { transform: 'rotate(0deg)' } },
        'ring-rotate': { from: { '--a': '0deg' }, to: { '--a': '360deg' } },
        wobble: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '20%': { transform: 'rotate(-14deg)' },
          '45%': { transform: 'rotate(14deg)' },
          '65%': { transform: 'rotate(-8deg)' },
          '85%': { transform: 'rotate(8deg)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-6px)' },
          '40%': { transform: 'translateX(6px)' },
          '60%': { transform: 'translateX(-4px)' },
          '80%': { transform: 'translateX(4px)' },
        },
        'loading-dots': { '0%': { content: '""' }, '33%': { content: '"."' }, '66%': { content: '".."' }, '100%': { content: '"..."' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
        breathe: 'breathe 3.2s cubic-bezier(0.65,0,0.35,1) infinite',
        bob: 'bob 4s ease-in-out infinite',
        'cue-bounce': 'cue-bounce 1.6s ease-in-out infinite',
        marquee: 'marquee 40s linear infinite',
        'marquee-slow': 'marquee 60s linear infinite',
        'spin-slow': 'spin-slow 40s linear infinite',
        'spin-rev': 'spin-rev 40s linear infinite',
        wobble: 'wobble 0.9s ease-in-out infinite',
        shake: 'shake 0.4s ease-in-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
